import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./(components)/theme.provider";
import { Jarkata } from "./fonts";
// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Jarkata.className} transition-colors duration-400`}>
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
